config/routes.rb
# @author Kevin Higgins
Rails.application.routes.draw do
  resources :course_modules
  resources :students

  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  get '/signout' => 'sessions#destroy'
  get '/signup' => 'users#new'
  post '/signup' => 'users#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course_module.rb
# @author Kevin Higgins
class CourseModule < ApplicationRecord
    has_many :students 
    validates_each :name, :description, :credits do |record, attr, value|
    if value.to_s.length < 1
      record.errors.add attr, 'is empty'
    end
    validates :credits, numericality: {:greater_than => 0, :only_integer => true, :message => 'must be a positive whole number' }
  end
end

app/models/student.rb
# @author Kevin Higgins
class Student < ApplicationRecord
  include ActiveModel::Validations
  belongs_to :course_module
  validates_each :name, :email do |record, attr, value|
    if value.to_s.length < 1
      record.errors.add attr, 'is empty'
    end
  end

end

app/models/user.rb
# @author Kevin Higgins
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
# @author Kevin Higgins
# this class uses some code, with modifications, from this tutorial https://gist.github.com/thebucknerlife/10090014
class ApplicationController < ActionController::Base

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
  def authorise
    if !current_user
      flash[:notice] = 'Only signed-in users may modify or create records.'
      redirect_to signin_path
    end
  end
end

app/controllers/course_modules_controller.rb
# @author Kevin Higgins
class CourseModulesController < ApplicationController
  before_action :set_course_module, only: [:show, :edit, :update, :destroy]
  before_action :authorise, only: [:edit, :update, :destroy]

  # GET /course_modules
  def index
    @course_modules = CourseModule.all
  end

  # GET /course_modules/1
  def show
  end

  # GET /course_modules/new
  def new
    @course_module = CourseModule.new
  end

  # GET /course_modules/1/edit
  def edit
  end

  # POST /course_modules
  def create
    @course_module = CourseModule.new(course_module_params)

    respond_to do |format|
      if @course_module.save
        format.html { redirect_to @course_module, notice: 'Module was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /course_modules/1
  def update
    respond_to do |format|
      if @course_module.update(course_module_params)
        format.html { redirect_to @course_module, notice: 'Module was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /course_modules/1
  def destroy
    @course_module.destroy
    respond_to do |format|
      format.html { redirect_to course_modules_url, notice: 'Module was successfully deleted.' }
      #format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_course_module
    @course_module = CourseModule.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def course_module_params
    params.require(:course_module).permit(:name, :description, :credits)
  end
end

app/controllers/sessions_controller.rb
# @author Kevin Higgins
# this class uses some code, with modifications, from this tutorial https://gist.github.com/thebucknerlife/10090014
class SessionsController < ApplicationController
  def new

  end
  def create
    user = User.find_by_email(params[:email])
    #puts 'User with email ' + params[:email] + ' exists ' + (user != nil).to_s
    #puts 'Password ' + params[:password].to_s + ' validates ' + (user.authenticate(params[:password])).to_s
    # in case of valid email and password
    if user && user.authenticate(params[:password])

      flash[:notice] = 'Welcome back, ' + user.name + '.'
      # save the user id inside the session variable hash
      session[:user_id] = user.id
      redirect_to students_path
    else
    # in case of invalid email or password, return to signin
      redirect_to signin_path
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to signin_path
  end
  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/students_controller.rb
# @author Kevin Higgins
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]
  before_action :authorise, only: [:edit, :update, :destroy]

  # GET /students
  def index
    @students = Student.all
  end

  # GET /students/1
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /students/1
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /students/1
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully deleted.' }
    end
  end

  private
  
  def set_student
    @student = Student.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def student_params
    params.require(:student).permit(:name, :email, :course_module_id, :paid)
  end
end

app/controllers/users_controller.rb
# @author Kevin Higgins
# this class uses some code, with modifications, from this tutorial https://gist.github.com/thebucknerlife/10090014
class UsersController < ApplicationController
  def new
    @user = User.new # this object is not used in view, but exists so view can poll it in case the view has been re-rendered due to an error
    # in which case the @user would actually be the user with errors that wasn't able to be created, built in the create method 
  end
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to students_path, notice: 'Sign-up successfully completed.' } # treat the student view as the home page
        #format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        #format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/course_modules_helper.rb
module CourseModulesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/course_modules/_form.html.erb
<!-- @author Kevin Higgins -->
<%= form_with(model: course_module, local: true) do |form| %>
  <% if course_module.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course_module.errors.count, "error") %> prohibited this module from being saved:</h2>

      <ul>
        <% course_module.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :credits %>
    <%= form.text_field :credits %>
  </div>

  <div class="actions">
    <%= form.submit 'Save module', :class => 'submit-button'%>
  </div>
<% end %>

app/views/course_modules/edit.html.erb
<!-- @author Kevin Higgins -->
<h1>Editing Module</h1>

<%= render 'form', course_module: @course_module %>

<%= link_to 'Show', @course_module %> |
<%= link_to 'Back', course_modules_path %>

app/views/course_modules/index.html.erb
<!-- @author Kevin Higgins -->
<p id="notice"><%= notice %></p>

<h2>Modules</h2>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Credits</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @course_modules.each do |course_module| %>
      <tr>
        <td><%= course_module.name %></td>
        <td><%= course_module.description %></td>
        <td><%= course_module.credits %></td>
        <td><%= link_to 'View', course_module %></td>
        <td><%= link_to 'Update', edit_course_module_path(course_module) %></td>
        <td><%= link_to 'Delete', course_module, method: :delete, data: { confirm: 'Do you wish to permanently delete this module?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New module', new_course_module_path %>

app/views/course_modules/new.html.erb
<!-- @author Kevin Higgins -->
<h2>New Module</h2>

<%= render 'form', course_module: @course_module %>

<%= link_to 'Back', course_modules_path %>

app/views/course_modules/show.html.erb
<!-- @author Kevin Higgins -->
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @course_module.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @course_module.description %>
</p>

<p>
  <strong>Credits:</strong>
  <%= @course_module.credits %>
</p>

<%= link_to 'Edit', edit_course_module_path(@course_module) %> |
<%= link_to 'Back', course_modules_path %>

app/views/layouts/application.html.erb
<!-- @author Kevin Higgins -->
<!DOCTYPE html>
<html>
  <head>
    <title>The Culinary Institute</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
    
  <body>
    <header>
        <nav>         
          <%= link_to 'Students', students_path, :class => 'top-link' %> 
          <%= link_to 'Modules', course_modules_path, :class => 'top-link' %> 

          <% if current_user %>
            <%= link_to 'Sign Out', signout_path, :class => 'top-link', :id => 'top-link-ender' %>
          <% else %>
            <%= link_to 'Sign In', signin_path, :class => 'top-link', :id => 'top-link-ender' %>
          <% end %>

      </nav>
    </header>
    <main>  
      <%= yield %>
    </main>
  </body>
</html>

app/views/students/_form.html.erb
<!-- @author Kevin Higgins -->
<%= form_with(model: student, local: true) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :course_module_id %>
    <%= form.collection_select(:course_module_id, CourseModule.all, :id, :name) %>
  </div>

  <div class="field">
    <%= form.label :paid %>
    <%= form.check_box :paid %>
  </div>

  <div class="actions">
    <%= form.submit 'Save student', :class => 'submit-button'%>
  </div>
<% end %>

app/views/students/edit.html.erb
<!-- @author Kevin Higgins -->
<h2>Editing Student</h2>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<!-- @author Kevin Higgins -->
<p id="notice"><%= notice %></p>

<h2>Students</h2>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th class="email-cell">Email</th>
      <th>Module</th>
      <th>Paid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td class="email-cell"><%= student.email %></td>
        <td>
          <% if student.course_module %>
            <%= student.course_module.name %>
          <% end %>
        </td>
        <td>
          <% if student.paid %>
            <%= 'Yes' %>
          <% else %>
            <%= 'No' %>
          <% end %>
        </td>
        <td><%= link_to 'View', student %></td>
        <td><%= link_to 'Update', edit_student_path(student) %></td>
        <td><%= link_to 'Delete', student, method: :delete, data: { confirm: 'Do you wish to permanently delete this student?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Add student', new_student_path %>

app/views/students/new.html.erb
<!-- @author Kevin Higgins -->
<h2>New Student</h2>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<!-- @author Kevin Higgins -->
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @student.email %>
</p>

<p>
  <strong>Module:</strong>
  <%= @student.course_module.name %>
</p>

<p>
  <strong>Paid:</strong>
	  <% if @student.paid %>
	    <%= 'Yes' %>
	  <% else %>
	    <%= 'No' %>
	  <% end %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>

app/views/users/new.html.erb
<!-- @author Kevin Higgins -->
<%= form_with(scope: :user, url: '/signup', method: 'post') do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% else %>
    <h2>Sign up</h2>
  
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field 'Password' %>
  </div>

  <div class="field">
    <%= form.label 'Confirm password' %>
    <%= form.password_field :password %>
  </div>

  <div class="actions">
    <%= form.submit 'Sign up', :class => 'submit-button'%>
  </div>
<% end %>